In [3]:
import numpy as np

def process_array(arr):
    print("Original Array:\n", arr)

    # Row-wise maximum replacement
    row_max = np.max(arr, axis=1, keepdims=True)
    row_replaced = np.repeat(row_max, arr.shape[1], axis=1)
    print("\nRow-wise max replaced:\n", row_replaced)

    # Column-wise minimum replacement
    col_min = np.min(arr, axis=0)
    col_replaced = np.repeat(col_min[np.newaxis, :], arr.shape[0], axis=0)
    print("\nColumn-wise min replaced:\n", col_replaced)


# Example usage
arr = np.random.randint(1, 101, (6, 6))
process_array(arr)

Original Array:
 [[20 49 79 11  7 39]
 [ 7 94 49 27 38 73]
 [ 2 42 57 45 59 33]
 [94 83 27 92 52 33]
 [43 76 42 19 40 17]
 [68 42 20 98 51 46]]

Row-wise max replaced:
 [[79 79 79 79 79 79]
 [94 94 94 94 94 94]
 [59 59 59 59 59 59]
 [94 94 94 94 94 94]
 [76 76 76 76 76 76]
 [98 98 98 98 98 98]]

Column-wise min replaced:
 [[ 2 42 20 11  7 17]
 [ 2 42 20 11  7 17]
 [ 2 42 20 11  7 17]
 [ 2 42 20 11  7 17]
 [ 2 42 20 11  7 17]
 [ 2 42 20 11  7 17]]


In [4]:
import numpy as np

def process_image(img):
    print("Original Image Shape:", img.shape)

    # Normalize to [0, 1]
    normalized = img / 255.0
    print("\nNormalized Image (0 to 1):\n", normalized)

    # Multiply by 5
    scaled = img * 5
    print("\nImage multiplied by 5:\n", scaled)


# Example usage
img = np.random.randint(0, 256, (512, 512))
process_image(img)

Original Image Shape: (512, 512)

Normalized Image (0 to 1):
 [[0.75686275 0.26666667 0.09019608 ... 0.01960784 0.92156863 0.63921569]
 [0.21176471 0.14901961 0.91764706 ... 0.61960784 0.37647059 0.27058824]
 [0.15294118 0.33333333 0.58039216 ... 0.3254902  0.10588235 0.72156863]
 ...
 [0.45098039 0.30196078 0.48235294 ... 0.75294118 0.38431373 0.6745098 ]
 [0.03137255 0.05098039 0.83921569 ... 0.16078431 0.49803922 0.76862745]
 [0.02745098 0.32941176 0.98431373 ... 0.03529412 0.34509804 0.01960784]]

Image multiplied by 5:
 [[ 965  340  115 ...   25 1175  815]
 [ 270  190 1170 ...  790  480  345]
 [ 195  425  740 ...  415  135  920]
 ...
 [ 575  385  615 ...  960  490  860]
 [  40   65 1070 ...  205  635  980]
 [  35  420 1255 ...   45  440   25]]
